#!/bin/bash

echo "macOS Persistence Scanner - Test Output"
echo "======================================"
echo ""
echo "Scanning for persistence mechanisms..."
echo ""
echo "Risk | Mechanism      | Label/Name                   | Path                                    | Program                                | Notes"
echo "-----|----------------|------------------------------|----------------------------------------|----------------------------------------|------------------------"
echo "High | LaunchAgent    | com.suspicious.agent         | ~/Library/LaunchAgents/com.suspicious.agent.plist | /tmp/suspicious_binary | RunAtLoad, KeepAlive, Binary in temporary directory"
echo "Med  | LaunchDaemon   | com.unknown.service          | /Library/LaunchDaemons/com.unknown.service.plist | /usr/local/bin/service | Unsigned binary"
echo "Low  | LaunchAgent    | com.legitimate.app           | ~/Library/LaunchAgents/com.legitimate.app.plist | /Applications/LegitApp.app/Contents/MacOS/LegitApp | Developer ID signed"
echo "Info | LaunchAgent    | com.apple.Safari             | /System/Library/LaunchAgents/com.apple.Safari.plist | /Applications/Safari.app/Contents/MacOS/Safari | Apple signed"
echo ""
echo "Scan completed in 1.234s"
echo "Total items found: 4"
echo ""
echo "Risk Summary:"
echo "  Critical: 0"
echo "  High: 1"
echo "  Medium: 1"
echo "  Low: 1"
echo "  Info: 1"